#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: #@ data.values.namespace
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx1
  namespace: #@ data.values.namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: #@ data.values.ingressDomain or assert.fail("missing ingressDomain")
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80