apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-credentials
  namespace: default
  annotations:
    build.pivotal.io/docker: https://${harbor_domain}
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Harbor12345
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: default
secrets:
  - name: harbor-registry-credentials