#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@overlay/match by=overlay.subset({"kind": "Gateway", "metadata":{"name": "istio-ingressgateway", "namespace": "cf-system"}})
---
spec:
  servers:
    #@overlay/match by=overlay.index(0)
    #@overlay/match-child-defaults missing_ok=True
    - tls:
        httpsRedirect: true
---
#! This certificate will cause cert-manager to create the secret istio-ingressgateway-certs
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  dnsNames:
  - #@ "*." + data.values.system_domain
#@ for/end domain in data.values.app_domains:
#@overlay/append
  - #@ "*." + domain
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

#! make sure the ingress cert secret isn't being created
#@overlay/match by=overlay.subset({"kind":"Secret","metadata":{"name":"istio-ingressgateway-certs","namespace":"istio-system"}})
#@overlay/remove